name: book_reader
description: "A book reader application."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  file_picker: ^9.2.0
  epubx: ^4.0.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  epub_view: ^3.2.0
  flutter_file_dialog: ^3.0.2
  image: ^3.3.0
  sqflite: ^2.4.1
  path: ^1.9.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_cover.png
    - assets/images/app_icon.png
